export type NotamProps = {
    id: string;
    number: string;
    qcode?: string | null;
    status?: string | null;
    category?: string | null;
    dist?: string | null;
    type?: string | null;
    issuedAt?: Date | null;
    location?: string | null;
    fir?: string | null;
    validFromRaw?: string | null;
    validToRaw?: string | null;
    validFrom?: Date | null;
    validTo?: Date | null;
    dailyWindowsRaw?: string | null;
    textE?: string | null;
    lowerLimit?: string | null;
    upperLimit?: string | null;
    geo?: string | null;
    geoUrl?: string | null;
    traffic?: string | null;
    purpose?: string | null;
    scope?: string | null;
    rawPayload?: string | null;
};
export declare class NotamModel {
    id: string;
    number: string;
    qcode?: string | null;
    status?: string | null;
    category?: string | null;
    dist?: string | null;
    type?: string | null;
    issuedAt?: Date | null;
    location?: string | null;
    fir?: string | null;
    validFromRaw?: string | null;
    validToRaw?: string | null;
    validFrom?: Date | null;
    validTo?: Date | null;
    dailyWindowsRaw?: string | null;
    textE?: string | null;
    lowerLimit?: string | null;
    upperLimit?: string | null;
    geo?: string | null;
    geoUrl?: string | null;
    traffic?: string | null;
    purpose?: string | null;
    scope?: string | null;
    rawPayload?: string | null;
    constructor(props: NotamProps);
}
